#!/usr/bin/env bash
#
# post-boilerplate.sh — runs on the trusted runner AFTER the sandbox finishes.
#
# The working tree in TARGET_REPO_DIR contains the boilerplate update plus any
# fixes the agent made. This stage — the only one with PUSH_TOKEN — commits the
# changes to a branch, pushes it, and opens a PR. If the agent reported
# `no_change` or produced no diff, it exits without opening a PR.
#
# Contract:
#   TARGET_REPO_DIR   — target repository checkout
#   REPO_FULL_NAME    — owner/repo for the PR
#   PUSH_TOKEN        — token with push + PR permissions
#   BOILERPLATE_BRANCH— branch to push to
#   GIT_BOT_EMAIL     — committer identity
#   FULLSEND_VALIDATED_ITERATION_DIR (preferred) — validated agent output dir
set -euo pipefail

REPO_DIR="${TARGET_REPO_DIR:-.}"
BRANCH="${BOILERPLATE_BRANCH:-chore/boilerplate-update}"
cd "${REPO_DIR}"

# Locate the agent result (prefer the validated iteration).
RESULT_DIR="${FULLSEND_VALIDATED_ITERATION_DIR:-}"
if [ -z "${RESULT_DIR}" ]; then
  RESULT_DIR="$(ls -d iteration-*/output 2>/dev/null | tail -1 || true)"
fi
RESULT_FILE="${RESULT_DIR:+${RESULT_DIR}/agent-result.json}"

STATUS="unknown"
SUMMARY="Automated OpenShift boilerplate update."
if [ -n "${RESULT_FILE:-}" ] && [ -f "${RESULT_FILE}" ]; then
  STATUS="$(jq -r '.status // "unknown"' "${RESULT_FILE}")"
  SUMMARY="$(jq -r '.summary // "Automated OpenShift boilerplate update."' "${RESULT_FILE}")"
fi

if [ "${STATUS}" = "no_change" ] || [ -z "$(git status --porcelain)" ]; then
  echo "No changes to submit; skipping PR."
  exit 0
fi

git config user.email "${GIT_BOT_EMAIL:-fullsend[bot]@users.noreply.github.com}"
git config user.name "fullsend-code"

git checkout -B "${BRANCH}"
git add -A
git commit -m "chore: update boilerplate

${SUMMARY}

Generated by the fullsend boilerplate maintenance agent."

REMOTE="https://x-access-token:${PUSH_TOKEN}@github.com/${REPO_FULL_NAME}.git"
git push --force-with-lease "${REMOTE}" "${BRANCH}"

PR_TITLE="chore: update boilerplate"
PR_BODY="${SUMMARY}

---
Automated by the fullsend boilerplate maintenance agent (agent status: ${STATUS}).
Review the convention changes under \`boilerplate/\` and any repo-side fixes."

# Create the PR if one doesn't already exist for this branch.
if ! GH_TOKEN="${PUSH_TOKEN}" gh pr view "${BRANCH}" --repo "${REPO_FULL_NAME}" >/dev/null 2>&1; then
  GH_TOKEN="${PUSH_TOKEN}" gh pr create \
    --repo "${REPO_FULL_NAME}" \
    --base master \
    --head "${BRANCH}" \
    --title "${PR_TITLE}" \
    --body "${PR_BODY}"
else
  echo "PR for ${BRANCH} already exists; branch updated."
fi
