apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: oao-monitoring-manager
  namespace: openshift-monitoring
  annotations:
    package-operator.run/phase: rbac
    package-operator.run/collision-protection: IfNoController
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: oao-monitoring-manager
subjects:
  - kind: ServiceAccount
    name: ocm-agent-operator
    namespace: openshift-ocm-agent-operator