//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentConfig) DeepCopyInto(out *AgentConfig) {
	*out = *in
	if in.Services != nil {
		in, out := &in.Services, &out.Services
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentConfig.
func (in *AgentConfig) DeepCopy() *AgentConfig {
	if in == nil {
		return nil
	}
	out := new(AgentConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in Conditions) DeepCopyInto(out *Conditions) {
	{
		in := &in
		*out = make(Conditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Conditions.
func (in Conditions) DeepCopy() Conditions {
	if in == nil {
		return nil
	}
	out := new(Conditions)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FleetNotification) DeepCopyInto(out *FleetNotification) {
	*out = *in
	if in.References != nil {
		in, out := &in.References, &out.References
		*out = make([]NotificationReferenceType, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FleetNotification.
func (in *FleetNotification) DeepCopy() *FleetNotification {
	if in == nil {
		return nil
	}
	out := new(FleetNotification)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedFleetNotification) DeepCopyInto(out *ManagedFleetNotification) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedFleetNotification.
func (in *ManagedFleetNotification) DeepCopy() *ManagedFleetNotification {
	if in == nil {
		return nil
	}
	out := new(ManagedFleetNotification)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManagedFleetNotification) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedFleetNotificationList) DeepCopyInto(out *ManagedFleetNotificationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ManagedFleetNotification, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedFleetNotificationList.
func (in *ManagedFleetNotificationList) DeepCopy() *ManagedFleetNotificationList {
	if in == nil {
		return nil
	}
	out := new(ManagedFleetNotificationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManagedFleetNotificationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedFleetNotificationRecord) DeepCopyInto(out *ManagedFleetNotificationRecord) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedFleetNotificationRecord.
func (in *ManagedFleetNotificationRecord) DeepCopy() *ManagedFleetNotificationRecord {
	if in == nil {
		return nil
	}
	out := new(ManagedFleetNotificationRecord)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManagedFleetNotificationRecord) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedFleetNotificationRecordList) DeepCopyInto(out *ManagedFleetNotificationRecordList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ManagedFleetNotificationRecord, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedFleetNotificationRecordList.
func (in *ManagedFleetNotificationRecordList) DeepCopy() *ManagedFleetNotificationRecordList {
	if in == nil {
		return nil
	}
	out := new(ManagedFleetNotificationRecordList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManagedFleetNotificationRecordList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedFleetNotificationRecordStatus) DeepCopyInto(out *ManagedFleetNotificationRecordStatus) {
	*out = *in
	if in.NotificationRecordByName != nil {
		in, out := &in.NotificationRecordByName, &out.NotificationRecordByName
		*out = make([]NotificationRecordByName, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedFleetNotificationRecordStatus.
func (in *ManagedFleetNotificationRecordStatus) DeepCopy() *ManagedFleetNotificationRecordStatus {
	if in == nil {
		return nil
	}
	out := new(ManagedFleetNotificationRecordStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedFleetNotificationSpec) DeepCopyInto(out *ManagedFleetNotificationSpec) {
	*out = *in
	in.FleetNotification.DeepCopyInto(&out.FleetNotification)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedFleetNotificationSpec.
func (in *ManagedFleetNotificationSpec) DeepCopy() *ManagedFleetNotificationSpec {
	if in == nil {
		return nil
	}
	out := new(ManagedFleetNotificationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedNotification) DeepCopyInto(out *ManagedNotification) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedNotification.
func (in *ManagedNotification) DeepCopy() *ManagedNotification {
	if in == nil {
		return nil
	}
	out := new(ManagedNotification)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManagedNotification) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedNotificationList) DeepCopyInto(out *ManagedNotificationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ManagedNotification, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedNotificationList.
func (in *ManagedNotificationList) DeepCopy() *ManagedNotificationList {
	if in == nil {
		return nil
	}
	out := new(ManagedNotificationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManagedNotificationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedNotificationSpec) DeepCopyInto(out *ManagedNotificationSpec) {
	*out = *in
	if in.Notifications != nil {
		in, out := &in.Notifications, &out.Notifications
		*out = make([]Notification, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedNotificationSpec.
func (in *ManagedNotificationSpec) DeepCopy() *ManagedNotificationSpec {
	if in == nil {
		return nil
	}
	out := new(ManagedNotificationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedNotificationStatus) DeepCopyInto(out *ManagedNotificationStatus) {
	*out = *in
	if in.NotificationRecords != nil {
		in, out := &in.NotificationRecords, &out.NotificationRecords
		*out = make(NotificationRecords, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedNotificationStatus.
func (in *ManagedNotificationStatus) DeepCopy() *ManagedNotificationStatus {
	if in == nil {
		return nil
	}
	out := new(ManagedNotificationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Notification) DeepCopyInto(out *Notification) {
	*out = *in
	if in.References != nil {
		in, out := &in.References, &out.References
		*out = make([]NotificationReferenceType, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Notification.
func (in *Notification) DeepCopy() *Notification {
	if in == nil {
		return nil
	}
	out := new(Notification)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationCondition) DeepCopyInto(out *NotificationCondition) {
	*out = *in
	if in.LastTransitionTime != nil {
		in, out := &in.LastTransitionTime, &out.LastTransitionTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationCondition.
func (in *NotificationCondition) DeepCopy() *NotificationCondition {
	if in == nil {
		return nil
	}
	out := new(NotificationCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationRecord) DeepCopyInto(out *NotificationRecord) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(Conditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationRecord.
func (in *NotificationRecord) DeepCopy() *NotificationRecord {
	if in == nil {
		return nil
	}
	out := new(NotificationRecord)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationRecordByName) DeepCopyInto(out *NotificationRecordByName) {
	*out = *in
	if in.NotificationRecordItems != nil {
		in, out := &in.NotificationRecordItems, &out.NotificationRecordItems
		*out = make([]NotificationRecordItem, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationRecordByName.
func (in *NotificationRecordByName) DeepCopy() *NotificationRecordByName {
	if in == nil {
		return nil
	}
	out := new(NotificationRecordByName)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationRecordItem) DeepCopyInto(out *NotificationRecordItem) {
	*out = *in
	if in.LastTransitionTime != nil {
		in, out := &in.LastTransitionTime, &out.LastTransitionTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationRecordItem.
func (in *NotificationRecordItem) DeepCopy() *NotificationRecordItem {
	if in == nil {
		return nil
	}
	out := new(NotificationRecordItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in NotificationRecords) DeepCopyInto(out *NotificationRecords) {
	{
		in := &in
		*out = make(NotificationRecords, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationRecords.
func (in NotificationRecords) DeepCopy() NotificationRecords {
	if in == nil {
		return nil
	}
	out := new(NotificationRecords)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OcmAgent) DeepCopyInto(out *OcmAgent) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OcmAgent.
func (in *OcmAgent) DeepCopy() *OcmAgent {
	if in == nil {
		return nil
	}
	out := new(OcmAgent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OcmAgent) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OcmAgentList) DeepCopyInto(out *OcmAgentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OcmAgent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OcmAgentList.
func (in *OcmAgentList) DeepCopy() *OcmAgentList {
	if in == nil {
		return nil
	}
	out := new(OcmAgentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OcmAgentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OcmAgentSpec) DeepCopyInto(out *OcmAgentSpec) {
	*out = *in
	in.AgentConfig.DeepCopyInto(&out.AgentConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OcmAgentSpec.
func (in *OcmAgentSpec) DeepCopy() *OcmAgentSpec {
	if in == nil {
		return nil
	}
	out := new(OcmAgentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OcmAgentStatus) DeepCopyInto(out *OcmAgentStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OcmAgentStatus.
func (in *OcmAgentStatus) DeepCopy() *OcmAgentStatus {
	if in == nil {
		return nil
	}
	out := new(OcmAgentStatus)
	in.DeepCopyInto(out)
	return out
}
