package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// OcmAgentSpec defines the desired state of OcmAgent
type OcmAgentSpec struct {
	// INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
	// Important: Run "operator-sdk generate k8s" to regenerate code after modifying this file
	// Add custom validation using kubebuilder tags: https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html

	// Environment defines the cluster env where the ocm agent will be running, support prod and stage
	Environment string `json:"environment"`

	// Services defines the supported OCM services, eg, service_log, cluster_management
	Services []string `json:"services"`

	// OcmAgentImage defines the image which will be used by the Ocm Agent
	OcmAgentImage string `json:"ocmAgentImage"`

	// TokenSecret points to the secret name which stores the access token to OCM server
	TokenSecret string `json:"tokenSecret"`

	// Replicas defines the replica count for the ocm agent service
	Replicas int32 `json:"replicas"`

	// OcmAgentConfig defines the configmap name which generated by operator and consumed by ocm agent service
	OcmAgentConfig string `json:"ocmAgentConfig"`
}

// OCMAgentStatus defines the observed state of OCMAgent
type OcmAgentStatus struct {
	// INSERT ADDITIONAL STATUS FIELDS - define observed state of cluster
	// Important: Run "operator-sdk generate k8s" to regenerate code after modifying this file
	// Add custom validation using kubebuilder tags: https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html

	// ServiceStatus indicates the status of ocm agent service
	ServiceStatus string `json:"serviceStatus"`

	// OcmUrl populates the ocm api endpoint from the spec.Environment
	OcmUrl string `json:"ocmUrl"`

	AvailableReplicas int32 `json:"availableReplicas"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// OcmAgent is the Schema for the ocmagents API
// +kubebuilder:subresource:status
// +kubebuilder:resource:path=ocmagents,scope=Namespaced
type OcmAgent struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   OcmAgentSpec   `json:"spec,omitempty"`
	Status OcmAgentStatus `json:"status,omitempty"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// OCMAgentList contains a list of OCMAgent
type OcmAgentList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []OcmAgent `json:"items"`
}

func init() {
	SchemeBuilder.Register(&OcmAgent{}, &OcmAgentList{})
}
